window.addEventListener("load",function(){
    let eid ="24880x728x90x4219x_ADSLOT1"; let eidi = eid+"i";
    let ifm = document.createElement("iframe");
        ifm.frameBorder=0;ifm.scrolling= "no";ifm.width= "728";ifm.height= "90";ifm.id=eidi;
        document.getElementById(eid).style.maxWidth = eid.split("x")[1] + "px";
        document.getElementById(eid).style.maxHeight = eid.split("x")[2] + "px";
    document.getElementById(eid).appendChild(ifm);
    let doc = document.getElementById(eidi).contentWindow.document;
    doc.write("<head><script type='text/javascript' src='https://cdn.pixfuture.com/djax_elastic.js'><\/script><\/head><div id=\""+eid+"\"></div><style>html,body{border: 0px;margin: 0px;padding: 0px;}</style>");
    var rlxaf = '';
rlxaf += "<"+"script type=\"text/javascript\">\n";
rlxaf += "var PWT={}; //Initialize Namespace\n";
rlxaf += "var pbjs = pbjs || {};\n";
rlxaf += "pbjs.que = pbjs.que || [];\n";
rlxaf += "var googletag = googletag || {};\n";
rlxaf += "googletag.cmd = googletag.cmd || [];\n";
rlxaf += "var gptRan = false;\n";
rlxaf += "PWT.jsLoaded = function(){ //PubMatic pwt.js on load callback is used to load GPT\n";
rlxaf += "loadGPT();\n";
rlxaf += "};\n";
rlxaf += "var loadGPT = function() {\n";
rlxaf += "// Check the gptRan flag\n";
rlxaf += "if (!gptRan) {\n";
rlxaf += "gptRan = true;\n";
rlxaf += "var gads = document.createElement(\'script\');\n";
rlxaf += "var useSSL = \'https:\' == document.location.protocol;\n";
rlxaf += "gads.src = (useSSL ? \'https:\' : \'http:\') + \'//www.googletagservices.com/tag/js/gpt.js\';\n";
rlxaf += "var node = document.getElementsByTagName(\'script\')[0];\n";
rlxaf += "node.parentNode.insertBefore(gads, node);\n";
rlxaf += "var pbjsEl = document.createElement(\"script\");\n";
rlxaf += "pbjsEl.type = \"text/javascript\";\n";
rlxaf += "pbjsEl.async = true;\n";
rlxaf += "pbjsEl.src = \"https://cdn.pixfuture.com/prebid4.19.0.js?v=3\";\n";
rlxaf += "var pbjsTargetEl = document.getElementsByTagName(\"head\")[0];\n";
rlxaf += "pbjsTargetEl.insertBefore(pbjsEl, pbjsTargetEl.firstChild);\n";
rlxaf += "}\n";
rlxaf += "};\n";
rlxaf += "// Failsafe to call gpt\n";
rlxaf += "setTimeout(loadGPT, 500);\n";
rlxaf += "<"+"/script>\n";
rlxaf += "<"+"script type=\"text/javascript\">\n";
rlxaf += "(function() {\n";
rlxaf += "var purl = window.location.href;\n";
rlxaf += "var url = \'//ads.pubmatic.com/AdServer/js/pwt/158127/2642\';\n";
rlxaf += "var profileVersionId = \'\';\n";
rlxaf += "if(purl.indexOf(\'pwtv=\')>0){\n";
rlxaf += "var regexp = /pwtv=(.*?)(&|$)/g;\n";
rlxaf += "var matches = regexp.exec(purl);\n";
rlxaf += "if(matches.length >= 2 && matches[1].length > 0){\n";
rlxaf += "profileVersionId = \'/\'+matches[1];\n";
rlxaf += "}\n";
rlxaf += "}\n";
rlxaf += "var wtads = document.createElement(\'script\');\n";
rlxaf += "wtads.async = true;\n";
rlxaf += "wtads.type = \'text/javascript\';\n";
rlxaf += "wtads.src = url+profileVersionId+\'/pwt.js\';\n";
rlxaf += "var node = document.getElementsByTagName(\'script\')[0];\n";
rlxaf += "node.parentNode.insertBefore(wtads, node);\n";
rlxaf += "})();\n";
rlxaf += "<"+"/script>\n";
rlxaf += "<"+"script type=\"text/javascript\">\n";
rlxaf += "function findCMP() {let f = window;let cmpFrame;let cmpFunction;while (!cmpFrame) {try {if (typeof f.__tcfapi === \'function\' || typeof f.__cmp === \'function\') {if (typeof f.__tcfapi === \'function\') {cmpVersion = 2;cmpFunction = f.__tcfapi;} else {cmpVersion = 1;cmpFunction = f.__cmp;}cmpFrame = f;break;}} catch (e) { }try {if (f.frames[\'__tcfapiLocator\']) {cmpVersion = 2;cmpFrame = f;break;}} catch (e) { }try {if (f.frames[\'__cmpLocator\']) {cmpVersion = 1;cmpFrame = f;break;}} catch (e) { }if (f === window.top) break;f = f.parent;}return {cmpFrame,cmpFunction};}\n";
rlxaf += "let { cmpFrame, cmpFunction } = findCMP();\n";
rlxaf += "var consent_module = \"\";\n";
rlxaf += "var file_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
rlxaf += "var t = 3;\n";
rlxaf += "var tout = 2000;\n";
rlxaf += "var site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
rlxaf += "var org_site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
rlxaf += "var mainDiv =\"pf-24880x728x90x4219x_ADSLOT1\";\n";
rlxaf += "var parent_ad_width = 728;\n";
rlxaf += "var parent_ad_height = 90;\n";
rlxaf += "if(parent_ad_width == 728 && parent_ad_height == 90) {\n";
rlxaf += "var flag_used = true;\n";
rlxaf += "} else {\n";
rlxaf += "var flag_used = false;\n";
rlxaf += "}\n";
rlxaf += "var int = new Array();\n";
rlxaf += "var pbjs = pbjs || {};\n";
rlxaf += "pbjs.que = pbjs.que || [];\n";
rlxaf += "var che = \"728\";\n";
rlxaf += "var sz = [\"24880x728x90x4219x_ADSLOT1\"];\n";
rlxaf += "var bz = [\"banner\"];\n";
rlxaf += "int[0]={\"24880x728x90x4219x_ADSLOT1\":{\"url\":\"<"+"script type=\\\"text\\/javascript\\\">var innerWidth = 1430;<"+"\\/script> <"+"!--pixfuture hbid71--> <"+"script type=\\\"text\\/javascript\\\">google_ad_client = \\\"ca-pub-1575911585432548\\\"; google_ad_slot = \\\"3157381981\\\"; google_ad_width = 728; google_ad_height = 90; <"+"\\/script> <"+"script type=\\\"text\\/javascript\\\" src=\\\"\\/\\/pagead2.googlesyndication.com\\/pagead\\/show_ads.js\\\"> <"+"\\/script>\",\"is_house\":1,\"cpm\":0,\"floor_price\":0,\"width\":\"728\",\"height\":\"90\",\"code\":\"4219\",\"zoneid\":\"24880\",\"adUnitCode\":\"24880x728x90x4219x_ADSLOT1\",\"type\":\"house\",\"third_share\":\"70\",\"int_share\":\"70\",\"passback\":\"<"+"script async src=\\\"https:\\/\\/pagead2.googlesyndication.com\\/pagead\\/js\\/adsbygoogle.js\\\"><"+"\\/script> <"+"!-- Display 728x90 --> <"+"ins class=\\\"adsbygoogle\\\" style=\\\"display:inline-block;width:728px;height:90px\\\" data-ad-client=\\\"ca-pub-3732773600888178\\\" data-ad-slot=\\\"1410653048\\\"><"+"\\/ins> <"+"script> (adsbygoogle = window.adsbygoogle || []).push({}); <"+"\\/script>\",\"campaignId\":7,\"bannerId\":33}};\n";
rlxaf += "var elobm = [\n";
rlxaf += "/*header-bidding-bidders*/\n";
rlxaf += "{\n";
rlxaf += "code:\"24880x728x90x4219x_ADSLOT1\",\n";
rlxaf += "mediaTypes: {banner: { sizes:[728,90]}},\n";
rlxaf += "bids: [{bidder : \"conversant\",params: {\"site_id\": \"202603\"}},{bidder : \"improvedigital\",params: {\"bidFloor\": 0.1,\"placementId\": 22292112}},{bidder : \"openx\",params: {\"customParams\": { \"myKeyword\": \"pokemon,icons,free,download,png,svg\",\"myOtherKeyword\": [\'pokemon\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"unit\": \"540580842\",\"delDomain\": \"pixfuture2-d.openx.net\"}},{bidder : \"smartadserver\",params: {\"target\": \"pokemon=pokemon|icons=icons|free=free|download=download|png=png|svg=svg\",\"formatId\": 0,\"pageId\": 1240155,\"siteId\": \"354470\"}},{bidder : \"33across\",params: {\"siteId\": \"azC7qard4r6OkMaKlId8sQ\",\"productId\": \"siab\"}},{bidder : \"synacormedia\",params: {\"seatId\": \"pixfuture\",\"placementId\": \"84884\",\"bidfloor\": 0.1,\"pos\": 1}},{bidder : \"appnexus\",params: {\"keywords\": { \"myKeyword\": \"pokemon,icons,free,download,png,svg\",\"myOtherKeyword\": [\'pokemon\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"placementId\": 15106105}},{bidder : \"aol\",params: {\"pos\": \"pixfuture_network_news_728x90\",\"dcn\": \"8a969105017575db4f32dc2eda5c0067\"}},{bidder : \"aol\",params: {\"network\": \"9834\",\"placement\": \"3344885\"}},{bidder : \"pubmatic\",params: {\"dctr\": \"pokemon=pokemon|icons=icons|free=free|download=download|png=png|svg=svg\",\"publisherId\": \"158127\",\"adSlot\": \"2069654\",\"kadfloor\": \"0.75\"}}]\n";
rlxaf += "}];\n";
rlxaf += "pbjs.que.push(function(){\n";
rlxaf += "pbjs.setConfig({\n";
rlxaf += "userSync: {\n";
rlxaf += "filterSettings: {\n";
rlxaf += "iframe: {\n";
rlxaf += "bidders: \"*\",\n";
rlxaf += "filter: \"include\"\n";
rlxaf += "}\n";
rlxaf += "},\n";
rlxaf += "userIds: [{\n";
rlxaf += "name: \"identityLink\",\n";
rlxaf += "params: {\n";
rlxaf += "pid: \'1258\'             // Set your real identityLink placement ID here\n";
rlxaf += "},\n";
rlxaf += "storage: {\n";
rlxaf += "type: \"cookie\",\n";
rlxaf += "name: \"idl_env\",       // create a cookie with this name\n";
rlxaf += "expires: 30            // cookie can last for 30 days\n";
rlxaf += "}\n";
rlxaf += "},{\n";
rlxaf += "name: \"unifiedId\",\n";
rlxaf += "params: {\n";
rlxaf += "partner: \"myTtdPid\",\n";
rlxaf += "url:\"https://match.adsrvr.org/track/rid?ttd_pid=pubmatic&fmt=json\"\n";
rlxaf += "},\n";
rlxaf += "storage: {\n";
rlxaf += "type: \"cookie\",\n";
rlxaf += "name: \"pbjs-unifiedid\",       // create a cookie with this name\n";
rlxaf += "expires: 60\n";
rlxaf += "}\n";
rlxaf += "},{\n";
rlxaf += "name: \"pubCommonId\",\n";
rlxaf += "storage: {\n";
rlxaf += "type: \"cookie\",\n";
rlxaf += "name: \"_pubcid\",     // create a cookie with this name\n";
rlxaf += "expires: 180\n";
rlxaf += "}\n";
rlxaf += "},{\n";
rlxaf += "name: \"criteo\",\n";
rlxaf += "}],\n";
rlxaf += "syncsPerBidder: 0,\n";
rlxaf += "syncDelay: 1000\n";
rlxaf += "},\n";
rlxaf += "schain: {\n";
rlxaf += "validation: \"strict\",\n";
rlxaf += "config: {\n";
rlxaf += "ver:\"1.0\",\n";
rlxaf += "complete: 1,\n";
rlxaf += "nodes: [\n";
rlxaf += "{\n";
rlxaf += "asi:\"pixfuture.com\",\n";
rlxaf += "sid:\"4219\",\n";
rlxaf += "hp:1\n";
rlxaf += "}\n";
rlxaf += "]\n";
rlxaf += "}\n";
rlxaf += "},\n";
rlxaf += "pubcid: {expInterval: 525600}      })\n";
rlxaf += "pbjs.bidderSettings = {conversant: {\n";
rlxaf += "bidCpmAdjustment: function (bidCpm, bid) {\n";
rlxaf += "return bidCpm * 0.87;\n";
rlxaf += "}\n";
rlxaf += "},synacormedia: {\n";
rlxaf += "bidCpmAdjustment: function (bidCpm, bid) {\n";
rlxaf += "return bidCpm * 0.85;\n";
rlxaf += "}\n";
rlxaf += "}};\n";
rlxaf += "if (!cmpFrame) {\n";
rlxaf += "console.log(\"CMP IS NOT FOUND!!!\");\n";
rlxaf += "}else{\n";
rlxaf += "pbjs.setConfig({\n";
rlxaf += "consentManagement: {gdpr: {cmpApi: \"iab\",timeout: 2000},usp: {timeout: 500}}\n";
rlxaf += "});\n";
rlxaf += "console.log(\"CMP IS FOUND\");\n";
rlxaf += "}\n";
rlxaf += "pbjs.requestBids({\n";
rlxaf += "adUnits:elobm,\n";
rlxaf += "bidsBackHandler: function(bidResponses) {\n";
rlxaf += "try {\n";
rlxaf += "//console.log(dome(elobm));\n";
rlxaf += "dome(elobm, false);\n";
rlxaf += "} catch (e) {\n";
rlxaf += "console.log(e);\n";
rlxaf += "console.log(\"retry sending request!!!!!!!\");\n";
rlxaf += "setTimeout(function(){\n";
rlxaf += "dome(elobm, false);\n";
rlxaf += "}, 300);\n";
rlxaf += "}\n";
rlxaf += "},\n";
rlxaf += "timeout: 2000,\n";
rlxaf += "});\n";
rlxaf += "});\n";
rlxaf += "var zone_id         = 24880;\n";
rlxaf += "function loadScript(url, callback) {\n";
rlxaf += "var script = document.createElement(\"script\")\n";
rlxaf += "script.type = \"text/javascript\";\n";
rlxaf += "if (script.readyState) {\n";
rlxaf += "script.onreadystatechange = function() {\n";
rlxaf += "if (script.readyState == \"loaded\" || script.readyState == \"complete\") {\n";
rlxaf += "script.onreadystatechange = null;\n";
rlxaf += "callback()\n";
rlxaf += "}\n";
rlxaf += "}\n";
rlxaf += "} else {\n";
rlxaf += "script.onload = function() {\n";
rlxaf += "callback()\n";
rlxaf += "}\n";
rlxaf += "}\n";
rlxaf += "script.src = url;\n";
rlxaf += "document.getElementsByTagName(\"head\")[0].appendChild(script)\n";
rlxaf += "}\n";
rlxaf += "<"+"/script>\n";
doc.write(rlxaf);
doc.close();});